export const countryData = [
  {
    CountryName: 'Somaliland',
    CapitalName: 'Hargeisa',
    CapitalLatitude: 9.55,
    CapitalLongitude: 44.05,
    ContinentName: 'Africa',
  },
  {
    CountryName: 'South Georgia and South Sandwich Islands',
    CapitalName: 'King Edward Point',
    CapitalLatitude: -54.283333,
    CapitalLongitude: -36.5,
    ContinentName: 'Antarctica',
  },
  {
    CountryName: 'French Southern and Antarctic Lands',
    CapitalName: 'Port-aux-Français',
    CapitalLatitude: -49.35,
    CapitalLongitude: 70.216667,
    ContinentName: 'Antarctica',
  },
  {
    CountryName: 'Israel',
    CapitalName: 'Jerusalem',
    CapitalLatitude: 31.76666667,
    CapitalLongitude: 35.233333,
    ContinentName: 'Asia',
  },
  {
    CountryName: 'Aland Islands',
    CapitalName: 'Mariehamn',
    CapitalLatitude: 60.116667,
    CapitalLongitude: 19.9,
    ContinentName: 'Europe',
  },
  {
    CountryName: 'Nauru',
    CapitalName: 'Yaren',
    CapitalLatitude: -0.5477,
    CapitalLongitude: 166.920867,
    ContinentName: 'Australia',
  },
  {
    CountryName: 'Saint Martin',
    CapitalName: 'Marigot',
    CapitalLatitude: 18.0731,
    CapitalLongitude: -63.0822,
    ContinentName: 'North America',
  },
  {
    CountryName: 'Tokelau',
    CapitalName: 'Atafu',
    CapitalLatitude: -9.166667,
    CapitalLongitude: -171.833333,
    ContinentName: 'Australia',
  },
  {
    CountryName: 'Afghanistan',
    CapitalName: 'Kabul',
    CapitalLatitude: 34.51666667,
    CapitalLongitude: 69.183333,
    ContinentName: 'Asia',
  },
  {
    CountryName: 'Albania',
    CapitalName: 'Tirana',
    CapitalLatitude: 41.31666667,
    CapitalLongitude: 19.816667,
    ContinentName: 'Europe',
  },
  {
    CountryName: 'Algeria',
    CapitalName: 'Algiers',
    CapitalLatitude: 36.75,
    CapitalLongitude: 3.05,
    ContinentName: 'Africa',
  },
  {
    CountryName: 'American Samoa',
    CapitalName: 'Pago Pago',
    CapitalLatitude: -14.26666667,
    CapitalLongitude: -170.7,
    ContinentName: 'Australia',
  },
  {
    CountryName: 'Andorra',
    CapitalName: 'Andorra la Vella',
    CapitalLatitude: 42.5,
    CapitalLongitude: 1.516667,
    ContinentName: 'Europe',
  },
  {
    CountryName: 'Angola',
    CapitalName: 'Luanda',
    CapitalLatitude: -8.833333333,
    CapitalLongitude: 13.216667,
    ContinentName: 'Africa',
  },
  {
    CountryName: 'Anguilla',
    CapitalName: 'The Valley',
    CapitalLatitude: 18.21666667,
    CapitalLongitude: -63.05,
    ContinentName: 'North America',
  },
  {
    CountryName: 'Antigua and Barbuda',
    CapitalName: "Saint John's",
    CapitalLatitude: 17.11666667,
    CapitalLongitude: -61.85,
    ContinentName: 'North America',
  },
  {
    CountryName: 'Argentina',
    CapitalName: 'Buenos Aires',
    CapitalLatitude: -34.58333333,
    CapitalLongitude: -58.666667,
    ContinentName: 'South America',
  },
  {
    CountryName: 'Armenia',
    CapitalName: 'Yerevan',
    CapitalLatitude: 40.16666667,
    CapitalLongitude: 44.5,
    ContinentName: 'Europe',
  },
  {
    CountryName: 'Aruba',
    CapitalName: 'Oranjestad',
    CapitalLatitude: 12.51666667,
    CapitalLongitude: -70.033333,
    ContinentName: 'North America',
  },
  {
    CountryName: 'Australia',
    CapitalName: 'Canberra',
    CapitalLatitude: -35.26666667,
    CapitalLongitude: 149.133333,
    ContinentName: 'Australia',
  },
  {
    CountryName: 'Austria',
    CapitalName: 'Vienna',
    CapitalLatitude: 48.2,
    CapitalLongitude: 16.366667,
    ContinentName: 'Europe',
  },
  {
    CountryName: 'Azerbaijan',
    CapitalName: 'Baku',
    CapitalLatitude: 40.38333333,
    CapitalLongitude: 49.866667,
    ContinentName: 'Europe',
  },
  {
    CountryName: 'Bahamas',
    CapitalName: 'Nassau',
    CapitalLatitude: 25.08333333,
    CapitalLongitude: -77.35,
    ContinentName: 'North America',
  },
  {
    CountryName: 'Bahrain',
    CapitalName: 'Manama',
    CapitalLatitude: 26.23333333,
    CapitalLongitude: 50.566667,
    ContinentName: 'Asia',
  },
  {
    CountryName: 'Bangladesh',
    CapitalName: 'Dhaka',
    CapitalLatitude: 23.71666667,
    CapitalLongitude: 90.4,
    ContinentName: 'Asia',
  },
  {
    CountryName: 'Barbados',
    CapitalName: 'Bridgetown',
    CapitalLatitude: 13.1,
    CapitalLongitude: -59.616667,
    ContinentName: 'North America',
  },
  {
    CountryName: 'Belarus',
    CapitalName: 'Minsk',
    CapitalLatitude: 53.9,
    CapitalLongitude: 27.566667,
    ContinentName: 'Europe',
  },
  {
    CountryName: 'Belgium',
    CapitalName: 'Brussels',
    CapitalLatitude: 50.83333333,
    CapitalLongitude: 4.333333,
    ContinentName: 'Europe',
  },
  {
    CountryName: 'Belize',
    CapitalName: 'Belmopan',
    CapitalLatitude: 17.25,
    CapitalLongitude: -88.766667,
    ContinentName: 'Central America',
  },
  {
    CountryName: 'Benin',
    CapitalName: 'Porto-Novo',
    CapitalLatitude: 6.483333333,
    CapitalLongitude: 2.616667,
    ContinentName: 'Africa',
  },
  {
    CountryName: 'Bermuda',
    CapitalName: 'Hamilton',
    CapitalLatitude: 32.28333333,
    CapitalLongitude: -64.783333,
    ContinentName: 'North America',
  },
  {
    CountryName: 'Bhutan',
    CapitalName: 'Thimphu',
    CapitalLatitude: 27.46666667,
    CapitalLongitude: 89.633333,
    ContinentName: 'Asia',
  },
  {
    CountryName: 'Bolivia',
    CapitalName: 'La Paz',
    CapitalLatitude: -16.5,
    CapitalLongitude: -68.15,
    ContinentName: 'South America',
  },
  {
    CountryName: 'Bosnia and Herzegovina',
    CapitalName: 'Sarajevo',
    CapitalLatitude: 43.86666667,
    CapitalLongitude: 18.416667,
    ContinentName: 'Europe',
  },
  {
    CountryName: 'Botswana',
    CapitalName: 'Gaborone',
    CapitalLatitude: -24.63333333,
    CapitalLongitude: 25.9,
    ContinentName: 'Africa',
  },
  {
    CountryName: 'Brazil',
    CapitalName: 'Brasilia',
    CapitalLatitude: -15.78333333,
    CapitalLongitude: -47.916667,
    ContinentName: 'South America',
  },
  {
    CountryName: 'British Virgin Islands',
    CapitalName: 'Road Town',
    CapitalLatitude: 18.41666667,
    CapitalLongitude: -64.616667,
    ContinentName: 'North America',
  },
  {
    CountryName: 'Brunei Darussalam',
    CapitalName: 'Bandar Seri Begawan',
    CapitalLatitude: 4.883333333,
    CapitalLongitude: 114.933333,
    ContinentName: 'Asia',
  },
  {
    CountryName: 'Bulgaria',
    CapitalName: 'Sofia',
    CapitalLatitude: 42.68333333,
    CapitalLongitude: 23.316667,
    ContinentName: 'Europe',
  },
  {
    CountryName: 'Burkina Faso',
    CapitalName: 'Ouagadougou',
    CapitalLatitude: 12.36666667,
    CapitalLongitude: -1.516667,
    ContinentName: 'Africa',
  },
  {
    CountryName: 'Myanmar',
    CapitalName: 'Rangoon',
    CapitalLatitude: 16.8,
    CapitalLongitude: 96.15,
    ContinentName: 'Asia',
  },
  {
    CountryName: 'Burundi',
    CapitalName: 'Bujumbura',
    CapitalLatitude: -3.366666667,
    CapitalLongitude: 29.35,
    ContinentName: 'Africa',
  },
  {
    CountryName: 'Cambodia',
    CapitalName: 'Phnom Penh',
    CapitalLatitude: 11.55,
    CapitalLongitude: 104.916667,
    ContinentName: 'Asia',
  },
  {
    CountryName: 'Cameroon',
    CapitalName: 'Yaounde',
    CapitalLatitude: 3.866666667,
    CapitalLongitude: 11.516667,
    ContinentName: 'Africa',
  },
  {
    CountryName: 'Canada',
    CapitalName: 'Ottawa',
    CapitalLatitude: 45.41666667,
    CapitalLongitude: -75.7,
    ContinentName: 'Central America',
  },
  {
    CountryName: 'Cape Verde',
    CapitalName: 'Praia',
    CapitalLatitude: 14.91666667,
    CapitalLongitude: -23.516667,
    ContinentName: 'Africa',
  },
  {
    CountryName: 'Cayman Islands',
    CapitalName: 'George Town',
    CapitalLatitude: 19.3,
    CapitalLongitude: -81.383333,
    ContinentName: 'North America',
  },
  {
    CountryName: 'Central African Republic',
    CapitalName: 'Bangui',
    CapitalLatitude: 4.366666667,
    CapitalLongitude: 18.583333,
    ContinentName: 'Africa',
  },
  {
    CountryName: 'Chad',
    CapitalName: "N'Djamena",
    CapitalLatitude: 12.1,
    CapitalLongitude: 15.033333,
    ContinentName: 'Africa',
  },
  {
    CountryName: 'Chile',
    CapitalName: 'Santiago',
    CapitalLatitude: -33.45,
    CapitalLongitude: -70.666667,
    ContinentName: 'South America',
  },
  {
    CountryName: 'China',
    CapitalName: 'Beijing',
    CapitalLatitude: 39.91666667,
    CapitalLongitude: 116.383333,
    ContinentName: 'Asia',
  },
  {
    CountryName: 'Christmas Island',
    CapitalName: 'The Settlement',
    CapitalLatitude: -10.41666667,
    CapitalLongitude: 105.716667,
    ContinentName: 'Australia',
  },
  {
    CountryName: 'Cocos Islands',
    CapitalName: 'West Island',
    CapitalLatitude: -12.16666667,
    CapitalLongitude: 96.833333,
    ContinentName: 'Australia',
  },
  {
    CountryName: 'Colombia',
    CapitalName: 'Bogota',
    CapitalLatitude: 4.6,
    CapitalLongitude: -74.083333,
    ContinentName: 'South America',
  },
  {
    CountryName: 'Comoros',
    CapitalName: 'Moroni',
    CapitalLatitude: -11.7,
    CapitalLongitude: 43.233333,
    ContinentName: 'Africa',
  },
  {
    CountryName: 'Democratic Republic of the Congo',
    CapitalName: 'Kinshasa',
    CapitalLatitude: -4.316666667,
    CapitalLongitude: 15.3,
    ContinentName: 'Africa',
  },
  {
    CountryName: 'Republic of Congo',
    CapitalName: 'Brazzaville',
    CapitalLatitude: -4.25,
    CapitalLongitude: 15.283333,
    ContinentName: 'Africa',
  },
  {
    CountryName: 'Cook Islands',
    CapitalName: 'Avarua',
    CapitalLatitude: -21.2,
    CapitalLongitude: -159.766667,
    ContinentName: 'Australia',
  },
  {
    CountryName: 'Costa Rica',
    CapitalName: 'San Jose',
    CapitalLatitude: 9.933333333,
    CapitalLongitude: -84.083333,
    ContinentName: 'Central America',
  },
  {
    CountryName: "Cote d'Ivoire",
    CapitalName: 'Yamoussoukro',
    CapitalLatitude: 6.816666667,
    CapitalLongitude: -5.266667,
    ContinentName: 'Africa',
  },
  {
    CountryName: 'Croatia',
    CapitalName: 'Zagreb',
    CapitalLatitude: 45.8,
    CapitalLongitude: 16,
    ContinentName: 'Europe',
  },
  {
    CountryName: 'Cuba',
    CapitalName: 'Havana',
    CapitalLatitude: 23.11666667,
    CapitalLongitude: -82.35,
    ContinentName: 'North America',
  },
  {
    CountryName: 'Curaçao',
    CapitalName: 'Willemstad',
    CapitalLatitude: 12.1,
    CapitalLongitude: -68.916667,
    ContinentName: 'North America',
  },
  {
    CountryName: 'Cyprus',
    CapitalName: 'Nicosia',
    CapitalLatitude: 35.16666667,
    CapitalLongitude: 33.366667,
    ContinentName: 'Europe',
  },
  {
    CountryName: 'Czech Republic',
    CapitalName: 'Prague',
    CapitalLatitude: 50.08333333,
    CapitalLongitude: 14.466667,
    ContinentName: 'Europe',
  },
  {
    CountryName: 'Denmark',
    CapitalName: 'Copenhagen',
    CapitalLatitude: 55.66666667,
    CapitalLongitude: 12.583333,
    ContinentName: 'Europe',
  },
  {
    CountryName: 'Djibouti',
    CapitalName: 'Djibouti',
    CapitalLatitude: 11.58333333,
    CapitalLongitude: 43.15,
    ContinentName: 'Africa',
  },
  {
    CountryName: 'Dominica',
    CapitalName: 'Roseau',
    CapitalLatitude: 15.3,
    CapitalLongitude: -61.4,
    ContinentName: 'North America',
  },
  {
    CountryName: 'Dominican Republic',
    CapitalName: 'Santo Domingo',
    CapitalLatitude: 18.46666667,
    CapitalLongitude: -69.9,
    ContinentName: 'North America',
  },
  {
    CountryName: 'Ecuador',
    CapitalName: 'Quito',
    CapitalLatitude: -0.216666667,
    CapitalLongitude: -78.5,
    ContinentName: 'South America',
  },
  {
    CountryName: 'Egypt',
    CapitalName: 'Cairo',
    CapitalLatitude: 30.05,
    CapitalLongitude: 31.25,
    ContinentName: 'Africa',
  },
  {
    CountryName: 'El Salvador',
    CapitalName: 'San Salvador',
    CapitalLatitude: 13.7,
    CapitalLongitude: -89.2,
    ContinentName: 'Central America',
  },
  {
    CountryName: 'Equatorial Guinea',
    CapitalName: 'Malabo',
    CapitalLatitude: 3.75,
    CapitalLongitude: 8.783333,
    ContinentName: 'Africa',
  },
  {
    CountryName: 'Eritrea',
    CapitalName: 'Asmara',
    CapitalLatitude: 15.33333333,
    CapitalLongitude: 38.933333,
    ContinentName: 'Africa',
  },
  {
    CountryName: 'Estonia',
    CapitalName: 'Tallinn',
    CapitalLatitude: 59.43333333,
    CapitalLongitude: 24.716667,
    ContinentName: 'Europe',
  },
  {
    CountryName: 'Ethiopia',
    CapitalName: 'Addis Ababa',
    CapitalLatitude: 9.033333333,
    CapitalLongitude: 38.7,
    ContinentName: 'Africa',
  },
  {
    CountryName: 'Falkland Islands',
    CapitalName: 'Stanley',
    CapitalLatitude: -51.7,
    CapitalLongitude: -57.85,
    ContinentName: 'South America',
  },
  {
    CountryName: 'Faroe Islands',
    CapitalName: 'Torshavn',
    CapitalLatitude: 62,
    CapitalLongitude: -6.766667,
    ContinentName: 'Europe',
  },
  {
    CountryName: 'Fiji',
    CapitalName: 'Suva',
    CapitalLatitude: -18.13333333,
    CapitalLongitude: 178.416667,
    ContinentName: 'Australia',
  },
  {
    CountryName: 'Finland',
    CapitalName: 'Helsinki',
    CapitalLatitude: 60.16666667,
    CapitalLongitude: 24.933333,
    ContinentName: 'Europe',
  },
  {
    CountryName: 'France',
    CapitalName: 'Paris',
    CapitalLatitude: 48.86666667,
    CapitalLongitude: 2.333333,
    ContinentName: 'Europe',
  },
  {
    CountryName: 'French Polynesia',
    CapitalName: 'Papeete',
    CapitalLatitude: -17.53333333,
    CapitalLongitude: -149.566667,
    ContinentName: 'Australia',
  },
  {
    CountryName: 'Gabon',
    CapitalName: 'Libreville',
    CapitalLatitude: 0.383333333,
    CapitalLongitude: 9.45,
    ContinentName: 'Africa',
  },
  {
    CountryName: 'The Gambia',
    CapitalName: 'Banjul',
    CapitalLatitude: 13.45,
    CapitalLongitude: -16.566667,
    ContinentName: 'Africa',
  },
  {
    CountryName: 'Georgia',
    CapitalName: 'Tbilisi',
    CapitalLatitude: 41.68333333,
    CapitalLongitude: 44.833333,
    ContinentName: 'Europe',
  },
  {
    CountryName: 'Germany',
    CapitalName: 'Berlin',
    CapitalLatitude: 52.51666667,
    CapitalLongitude: 13.4,
    ContinentName: 'Europe',
  },
  {
    CountryName: 'Ghana',
    CapitalName: 'Accra',
    CapitalLatitude: 5.55,
    CapitalLongitude: -0.216667,
    ContinentName: 'Africa',
  },
  {
    CountryName: 'Gibraltar',
    CapitalName: 'Gibraltar',
    CapitalLatitude: 36.13333333,
    CapitalLongitude: -5.35,
    ContinentName: 'Europe',
  },
  {
    CountryName: 'Greece',
    CapitalName: 'Athens',
    CapitalLatitude: 37.98333333,
    CapitalLongitude: 23.733333,
    ContinentName: 'Europe',
  },
  {
    CountryName: 'Greenland',
    CapitalName: 'Nuuk',
    CapitalLatitude: 64.18333333,
    CapitalLongitude: -51.75,
    ContinentName: 'Central America',
  },
  {
    CountryName: 'Grenada',
    CapitalName: "Saint George's",
    CapitalLatitude: 12.05,
    CapitalLongitude: -61.75,
    ContinentName: 'North America',
  },
  {
    CountryName: 'Guam',
    CapitalName: 'Hagatna',
    CapitalLatitude: 13.46666667,
    CapitalLongitude: 144.733333,
    ContinentName: 'Australia',
  },
  {
    CountryName: 'Guatemala',
    CapitalName: 'Guatemala City',
    CapitalLatitude: 14.61666667,
    CapitalLongitude: -90.516667,
    ContinentName: 'Central America',
  },
  {
    CountryName: 'Guernsey',
    CapitalName: 'Saint Peter Port',
    CapitalLatitude: 49.45,
    CapitalLongitude: -2.533333,
    ContinentName: 'Europe',
  },
  {
    CountryName: 'Guinea',
    CapitalName: 'Conakry',
    CapitalLatitude: 9.5,
    CapitalLongitude: -13.7,
    ContinentName: 'Africa',
  },
  {
    CountryName: 'Guinea-Bissau',
    CapitalName: 'Bissau',
    CapitalLatitude: 11.85,
    CapitalLongitude: -15.583333,
    ContinentName: 'Africa',
  },
  {
    CountryName: 'Guyana',
    CapitalName: 'Georgetown',
    CapitalLatitude: 6.8,
    CapitalLongitude: -58.15,
    ContinentName: 'South America',
  },
  {
    CountryName: 'Haiti',
    CapitalName: 'Port-au-Prince',
    CapitalLatitude: 18.53333333,
    CapitalLongitude: -72.333333,
    ContinentName: 'North America',
  },
  {
    CountryName: 'Vatican City',
    CapitalName: 'Vatican City',
    CapitalLatitude: 41.9,
    CapitalLongitude: 12.45,
    ContinentName: 'Europe',
  },
  {
    CountryName: 'Honduras',
    CapitalName: 'Tegucigalpa',
    CapitalLatitude: 14.1,
    CapitalLongitude: -87.216667,
    ContinentName: 'Central America',
  },
  {
    CountryName: 'Hungary',
    CapitalName: 'Budapest',
    CapitalLatitude: 47.5,
    CapitalLongitude: 19.083333,
    ContinentName: 'Europe',
  },
  {
    CountryName: 'Iceland',
    CapitalName: 'Reykjavik',
    CapitalLatitude: 64.15,
    CapitalLongitude: -21.95,
    ContinentName: 'Europe',
  },
  {
    CountryName: 'India',
    CapitalName: 'New Delhi',
    CapitalLatitude: 28.6,
    CapitalLongitude: 77.2,
    ContinentName: 'Asia',
  },
  {
    CountryName: 'Indonesia',
    CapitalName: 'Jakarta',
    CapitalLatitude: -6.166666667,
    CapitalLongitude: 106.816667,
    ContinentName: 'Asia',
  },
  {
    CountryName: 'Iran',
    CapitalName: 'Tehran',
    CapitalLatitude: 35.7,
    CapitalLongitude: 51.416667,
    ContinentName: 'Asia',
  },
  {
    CountryName: 'Iraq',
    CapitalName: 'Baghdad',
    CapitalLatitude: 33.33333333,
    CapitalLongitude: 44.4,
    ContinentName: 'Asia',
  },
  {
    CountryName: 'Ireland',
    CapitalName: 'Dublin',
    CapitalLatitude: 53.31666667,
    CapitalLongitude: -6.233333,
    ContinentName: 'Europe',
  },
  {
    CountryName: 'Isle of Man',
    CapitalName: 'Douglas',
    CapitalLatitude: 54.15,
    CapitalLongitude: -4.483333,
    ContinentName: 'Europe',
  },
  {
    CountryName: 'Israel',
    CapitalName: 'Jerusalem',
    CapitalLatitude: 31.76666667,
    CapitalLongitude: 35.233333,
    ContinentName: 'Asia',
  },
  {
    CountryName: 'Italy',
    CapitalName: 'Rome',
    CapitalLatitude: 41.9,
    CapitalLongitude: 12.483333,
    ContinentName: 'Europe',
  },
  {
    CountryName: 'Jamaica',
    CapitalName: 'Kingston',
    CapitalLatitude: 18,
    CapitalLongitude: -76.8,
    ContinentName: 'North America',
  },
  {
    CountryName: 'Japan',
    CapitalName: 'Tokyo',
    CapitalLatitude: 35.68333333,
    CapitalLongitude: 139.75,
    ContinentName: 'Asia',
  },
  {
    CountryName: 'Jersey',
    CapitalName: 'Saint Helier',
    CapitalLatitude: 49.18333333,
    CapitalLongitude: -2.1,
    ContinentName: 'Europe',
  },
  {
    CountryName: 'Jordan',
    CapitalName: 'Amman',
    CapitalLatitude: 31.95,
    CapitalLongitude: 35.933333,
    ContinentName: 'Asia',
  },
  {
    CountryName: 'Kazakhstan',
    CapitalName: 'Astana',
    CapitalLatitude: 51.16666667,
    CapitalLongitude: 71.416667,
    ContinentName: 'Asia',
  },
  {
    CountryName: 'Kenya',
    CapitalName: 'Nairobi',
    CapitalLatitude: -1.283333333,
    CapitalLongitude: 36.816667,
    ContinentName: 'Africa',
  },
  {
    CountryName: 'Kiribati',
    CapitalName: 'Tarawa',
    CapitalLatitude: -0.883333333,
    CapitalLongitude: 169.533333,
    ContinentName: 'Australia',
  },
  {
    CountryName: 'North Korea',
    CapitalName: 'Pyongyang',
    CapitalLatitude: 39.01666667,
    CapitalLongitude: 125.75,
    ContinentName: 'Asia',
  },
  {
    CountryName: 'South Korea',
    CapitalName: 'Seoul',
    CapitalLatitude: 37.55,
    CapitalLongitude: 126.983333,
    ContinentName: 'Asia',
  },
  {
    CountryName: 'Kosovo',
    CapitalName: 'Pristina',
    CapitalLatitude: 42.66666667,
    CapitalLongitude: 21.166667,
    ContinentName: 'Europe',
  },
  {
    CountryName: 'Kuwait',
    CapitalName: 'Kuwait City',
    CapitalLatitude: 29.36666667,
    CapitalLongitude: 47.966667,
    ContinentName: 'Asia',
  },
  {
    CountryName: 'Kyrgyzstan',
    CapitalName: 'Bishkek',
    CapitalLatitude: 42.86666667,
    CapitalLongitude: 74.6,
    ContinentName: 'Asia',
  },
  {
    CountryName: 'Laos',
    CapitalName: 'Vientiane',
    CapitalLatitude: 17.96666667,
    CapitalLongitude: 102.6,
    ContinentName: 'Asia',
  },
  {
    CountryName: 'Latvia',
    CapitalName: 'Riga',
    CapitalLatitude: 56.95,
    CapitalLongitude: 24.1,
    ContinentName: 'Europe',
  },
  {
    CountryName: 'Lebanon',
    CapitalName: 'Beirut',
    CapitalLatitude: 33.86666667,
    CapitalLongitude: 35.5,
    ContinentName: 'Asia',
  },
  {
    CountryName: 'Lesotho',
    CapitalName: 'Maseru',
    CapitalLatitude: -29.31666667,
    CapitalLongitude: 27.483333,
    ContinentName: 'Africa',
  },
  {
    CountryName: 'Liberia',
    CapitalName: 'Monrovia',
    CapitalLatitude: 6.3,
    CapitalLongitude: -10.8,
    ContinentName: 'Africa',
  },
  {
    CountryName: 'Libya',
    CapitalName: 'Tripoli',
    CapitalLatitude: 32.88333333,
    CapitalLongitude: 13.166667,
    ContinentName: 'Africa',
  },
  {
    CountryName: 'Liechtenstein',
    CapitalName: 'Vaduz',
    CapitalLatitude: 47.13333333,
    CapitalLongitude: 9.516667,
    ContinentName: 'Europe',
  },
  {
    CountryName: 'Lithuania',
    CapitalName: 'Vilnius',
    CapitalLatitude: 54.68333333,
    CapitalLongitude: 25.316667,
    ContinentName: 'Europe',
  },
  {
    CountryName: 'Luxembourg',
    CapitalName: 'Luxembourg',
    CapitalLatitude: 49.6,
    CapitalLongitude: 6.116667,
    ContinentName: 'Europe',
  },
  {
    CountryName: 'Macedonia',
    CapitalName: 'Skopje',
    CapitalLatitude: 42,
    CapitalLongitude: 21.433333,
    ContinentName: 'Europe',
  },
  {
    CountryName: 'Madagascar',
    CapitalName: 'Antananarivo',
    CapitalLatitude: -18.91666667,
    CapitalLongitude: 47.516667,
    ContinentName: 'Africa',
  },
  {
    CountryName: 'Malawi',
    CapitalName: 'Lilongwe',
    CapitalLatitude: -13.96666667,
    CapitalLongitude: 33.783333,
    ContinentName: 'Africa',
  },
  {
    CountryName: 'Malaysia',
    CapitalName: 'Kuala Lumpur',
    CapitalLatitude: 3.166666667,
    CapitalLongitude: 101.7,
    ContinentName: 'Asia',
  },
  {
    CountryName: 'Maldives',
    CapitalName: 'Male',
    CapitalLatitude: 4.166666667,
    CapitalLongitude: 73.5,
    ContinentName: 'Asia',
  },
  {
    CountryName: 'Mali',
    CapitalName: 'Bamako',
    CapitalLatitude: 12.65,
    CapitalLongitude: -8,
    ContinentName: 'Africa',
  },
  {
    CountryName: 'Malta',
    CapitalName: 'Valletta',
    CapitalLatitude: 35.88333333,
    CapitalLongitude: 14.5,
    ContinentName: 'Europe',
  },
  {
    CountryName: 'Marshall Islands',
    CapitalName: 'Majuro',
    CapitalLatitude: 7.1,
    CapitalLongitude: 171.383333,
    ContinentName: 'Australia',
  },
  {
    CountryName: 'Mauritania',
    CapitalName: 'Nouakchott',
    CapitalLatitude: 18.06666667,
    CapitalLongitude: -15.966667,
    ContinentName: 'Africa',
  },
  {
    CountryName: 'Mauritius',
    CapitalName: 'Port Louis',
    CapitalLatitude: -20.15,
    CapitalLongitude: 57.483333,
    ContinentName: 'Africa',
  },
  {
    CountryName: 'Mexico',
    CapitalName: 'Mexico City',
    CapitalLatitude: 19.43333333,
    CapitalLongitude: -99.133333,
    ContinentName: 'Central America',
  },
  {
    CountryName: 'Federated States of Micronesia',
    CapitalName: 'Palikir',
    CapitalLatitude: 6.916666667,
    CapitalLongitude: 158.15,
    ContinentName: 'Australia',
  },
  {
    CountryName: 'Moldova',
    CapitalName: 'Chisinau',
    CapitalLatitude: 47,
    CapitalLongitude: 28.85,
    ContinentName: 'Europe',
  },
  {
    CountryName: 'Monaco',
    CapitalName: 'Monaco',
    CapitalLatitude: 43.73333333,
    CapitalLongitude: 7.416667,
    ContinentName: 'Europe',
  },
  {
    CountryName: 'Mongolia',
    CapitalName: 'Ulaanbaatar',
    CapitalLatitude: 47.91666667,
    CapitalLongitude: 106.916667,
    ContinentName: 'Asia',
  },
  {
    CountryName: 'Montenegro',
    CapitalName: 'Podgorica',
    CapitalLatitude: 42.43333333,
    CapitalLongitude: 19.266667,
    ContinentName: 'Europe',
  },
  {
    CountryName: 'Montserrat',
    CapitalName: 'Plymouth',
    CapitalLatitude: 16.7,
    CapitalLongitude: -62.216667,
    ContinentName: 'North America',
  },
  {
    CountryName: 'Morocco',
    CapitalName: 'Rabat',
    CapitalLatitude: 34.01666667,
    CapitalLongitude: -6.816667,
    ContinentName: 'Africa',
  },
  {
    CountryName: 'Mozambique',
    CapitalName: 'Maputo',
    CapitalLatitude: -25.95,
    CapitalLongitude: 32.583333,
    ContinentName: 'Africa',
  },
  {
    CountryName: 'Namibia',
    CapitalName: 'Windhoek',
    CapitalLatitude: -22.56666667,
    CapitalLongitude: 17.083333,
    ContinentName: 'Africa',
  },
  {
    CountryName: 'Nepal',
    CapitalName: 'Kathmandu',
    CapitalLatitude: 27.71666667,
    CapitalLongitude: 85.316667,
    ContinentName: 'Asia',
  },
  {
    CountryName: 'Netherlands',
    CapitalName: 'Amsterdam',
    CapitalLatitude: 52.35,
    CapitalLongitude: 4.916667,
    ContinentName: 'Europe',
  },
  {
    CountryName: 'New Caledonia',
    CapitalName: 'Noumea',
    CapitalLatitude: -22.26666667,
    CapitalLongitude: 166.45,
    ContinentName: 'Australia',
  },
  {
    CountryName: 'New Zealand',
    CapitalName: 'Wellington',
    CapitalLatitude: -41.3,
    CapitalLongitude: 174.783333,
    ContinentName: 'Australia',
  },
  {
    CountryName: 'Nicaragua',
    CapitalName: 'Managua',
    CapitalLatitude: 12.13333333,
    CapitalLongitude: -86.25,
    ContinentName: 'Central America',
  },
  {
    CountryName: 'Niger',
    CapitalName: 'Niamey',
    CapitalLatitude: 13.51666667,
    CapitalLongitude: 2.116667,
    ContinentName: 'Africa',
  },
  {
    CountryName: 'Nigeria',
    CapitalName: 'Abuja',
    CapitalLatitude: 9.083333333,
    CapitalLongitude: 7.533333,
    ContinentName: 'Africa',
  },
  {
    CountryName: 'Niue',
    CapitalName: 'Alofi',
    CapitalLatitude: -19.01666667,
    CapitalLongitude: -169.916667,
    ContinentName: 'Australia',
  },
  {
    CountryName: 'Norfolk Island',
    CapitalName: 'Kingston',
    CapitalLatitude: -29.05,
    CapitalLongitude: 167.966667,
    ContinentName: 'Australia',
  },
  {
    CountryName: 'Northern Mariana Islands',
    CapitalName: 'Saipan',
    CapitalLatitude: 15.2,
    CapitalLongitude: 145.75,
    ContinentName: 'Australia',
  },
  {
    CountryName: 'Norway',
    CapitalName: 'Oslo',
    CapitalLatitude: 59.91666667,
    CapitalLongitude: 10.75,
    ContinentName: 'Europe',
  },
  {
    CountryName: 'Oman',
    CapitalName: 'Muscat',
    CapitalLatitude: 23.61666667,
    CapitalLongitude: 58.583333,
    ContinentName: 'Asia',
  },
  {
    CountryName: 'Pakistan',
    CapitalName: 'Islamabad',
    CapitalLatitude: 33.68333333,
    CapitalLongitude: 73.05,
    ContinentName: 'Asia',
  },
  {
    CountryName: 'Palau',
    CapitalName: 'Melekeok',
    CapitalLatitude: 7.483333333,
    CapitalLongitude: 134.633333,
    ContinentName: 'Australia',
  },
  {
    CountryName: 'Panama',
    CapitalName: 'Panama City',
    CapitalLatitude: 8.966666667,
    CapitalLongitude: -79.533333,
    ContinentName: 'Central America',
  },
  {
    CountryName: 'Papua New Guinea',
    CapitalName: 'Port Moresby',
    CapitalLatitude: -9.45,
    CapitalLongitude: 147.183333,
    ContinentName: 'Australia',
  },
  {
    CountryName: 'Paraguay',
    CapitalName: 'Asuncion',
    CapitalLatitude: -25.26666667,
    CapitalLongitude: -57.666667,
    ContinentName: 'South America',
  },
  {
    CountryName: 'Peru',
    CapitalName: 'Lima',
    CapitalLatitude: -12.05,
    CapitalLongitude: -77.05,
    ContinentName: 'South America',
  },
  {
    CountryName: 'Philippines',
    CapitalName: 'Manila',
    CapitalLatitude: 14.6,
    CapitalLongitude: 120.966667,
    ContinentName: 'Asia',
  },
  {
    CountryName: 'Pitcairn Islands',
    CapitalName: 'Adamstown',
    CapitalLatitude: -25.06666667,
    CapitalLongitude: -130.083333,
    ContinentName: 'Australia',
  },
  {
    CountryName: 'Poland',
    CapitalName: 'Warsaw',
    CapitalLatitude: 52.25,
    CapitalLongitude: 21,
    ContinentName: 'Europe',
  },
  {
    CountryName: 'Portugal',
    CapitalName: 'Lisbon',
    CapitalLatitude: 38.71666667,
    CapitalLongitude: -9.133333,
    ContinentName: 'Europe',
  },
  {
    CountryName: 'Puerto Rico',
    CapitalName: 'San Juan',
    CapitalLatitude: 18.46666667,
    CapitalLongitude: -66.116667,
    ContinentName: 'North America',
  },
  {
    CountryName: 'Qatar',
    CapitalName: 'Doha',
    CapitalLatitude: 25.28333333,
    CapitalLongitude: 51.533333,
    ContinentName: 'Asia',
  },
  {
    CountryName: 'Romania',
    CapitalName: 'Bucharest',
    CapitalLatitude: 44.43333333,
    CapitalLongitude: 26.1,
    ContinentName: 'Europe',
  },
  {
    CountryName: 'Russia',
    CapitalName: 'Moscow',
    CapitalLatitude: 55.75,
    CapitalLongitude: 37.6,
    ContinentName: 'Europe',
  },
  {
    CountryName: 'Rwanda',
    CapitalName: 'Kigali',
    CapitalLatitude: -1.95,
    CapitalLongitude: 30.05,
    ContinentName: 'Africa',
  },
  {
    CountryName: 'Saint Barthelemy',
    CapitalName: 'Gustavia',
    CapitalLatitude: 17.88333333,
    CapitalLongitude: -62.85,
    ContinentName: 'North America',
  },
  {
    CountryName: 'Saint Helena',
    CapitalName: 'Jamestown',
    CapitalLatitude: -15.93333333,
    CapitalLongitude: -5.716667,
    ContinentName: 'Africa',
  },
  {
    CountryName: 'Saint Kitts and Nevis',
    CapitalName: 'Basseterre',
    CapitalLatitude: 17.3,
    CapitalLongitude: -62.716667,
    ContinentName: 'North America',
  },
  {
    CountryName: 'Saint Lucia',
    CapitalName: 'Castries',
    CapitalLatitude: 14,
    CapitalLongitude: -61,
    ContinentName: 'North America',
  },
  {
    CountryName: 'Saint Pierre and Miquelon',
    CapitalName: 'Saint-Pierre',
    CapitalLatitude: 46.76666667,
    CapitalLongitude: -56.183333,
    ContinentName: 'Central America',
  },
  {
    CountryName: 'Saint Vincent and the Grenadines',
    CapitalName: 'Kingstown',
    CapitalLatitude: 13.13333333,
    CapitalLongitude: -61.216667,
    ContinentName: 'Central America',
  },
  {
    CountryName: 'Samoa',
    CapitalName: 'Apia',
    CapitalLatitude: -13.81666667,
    CapitalLongitude: -171.766667,
    ContinentName: 'Australia',
  },
  {
    CountryName: 'San Marino',
    CapitalName: 'San Marino',
    CapitalLatitude: 43.93333333,
    CapitalLongitude: 12.416667,
    ContinentName: 'Europe',
  },
  {
    CountryName: 'Sao Tome and Principe',
    CapitalName: 'Sao Tome',
    CapitalLatitude: 0.333333333,
    CapitalLongitude: 6.733333,
    ContinentName: 'Africa',
  },
  {
    CountryName: 'Saudi Arabia',
    CapitalName: 'Riyadh',
    CapitalLatitude: 24.65,
    CapitalLongitude: 46.7,
    ContinentName: 'Asia',
  },
  {
    CountryName: 'Senegal',
    CapitalName: 'Dakar',
    CapitalLatitude: 14.73333333,
    CapitalLongitude: -17.633333,
    ContinentName: 'Africa',
  },
  {
    CountryName: 'Serbia',
    CapitalName: 'Belgrade',
    CapitalLatitude: 44.83333333,
    CapitalLongitude: 20.5,
    ContinentName: 'Europe',
  },
  {
    CountryName: 'Seychelles',
    CapitalName: 'Victoria',
    CapitalLatitude: -4.616666667,
    CapitalLongitude: 55.45,
    ContinentName: 'Africa',
  },
  {
    CountryName: 'Sierra Leone',
    CapitalName: 'Freetown',
    CapitalLatitude: 8.483333333,
    CapitalLongitude: -13.233333,
    ContinentName: 'Africa',
  },
  {
    CountryName: 'Singapore',
    CapitalName: 'Singapore',
    CapitalLatitude: 1.283333333,
    CapitalLongitude: 103.85,
    ContinentName: 'Asia',
  },
  {
    CountryName: 'Sint Maarten',
    CapitalName: 'Philipsburg',
    CapitalLatitude: 18.01666667,
    CapitalLongitude: -63.033333,
    ContinentName: 'North America',
  },
  {
    CountryName: 'Slovakia',
    CapitalName: 'Bratislava',
    CapitalLatitude: 48.15,
    CapitalLongitude: 17.116667,
    ContinentName: 'Europe',
  },
  {
    CountryName: 'Slovenia',
    CapitalName: 'Ljubljana',
    CapitalLatitude: 46.05,
    CapitalLongitude: 14.516667,
    ContinentName: 'Europe',
  },
  {
    CountryName: 'Solomon Islands',
    CapitalName: 'Honiara',
    CapitalLatitude: -9.433333333,
    CapitalLongitude: 159.95,
    ContinentName: 'Australia',
  },
  {
    CountryName: 'Somalia',
    CapitalName: 'Mogadishu',
    CapitalLatitude: 2.066666667,
    CapitalLongitude: 45.333333,
    ContinentName: 'Africa',
  },
  {
    CountryName: 'South Africa',
    CapitalName: 'Pretoria',
    CapitalLatitude: -25.7,
    CapitalLongitude: 28.216667,
    ContinentName: 'Africa',
  },
  {
    CountryName: 'South Sudan',
    CapitalName: 'Juba',
    CapitalLatitude: 4.85,
    CapitalLongitude: 31.616667,
    ContinentName: 'Africa',
  },
  {
    CountryName: 'Spain',
    CapitalName: 'Madrid',
    CapitalLatitude: 40.4,
    CapitalLongitude: -3.683333,
    ContinentName: 'Europe',
  },
  {
    CountryName: 'Sri Lanka',
    CapitalName: 'Colombo',
    CapitalLatitude: 6.916666667,
    CapitalLongitude: 79.833333,
    ContinentName: 'Asia',
  },
  {
    CountryName: 'Sudan',
    CapitalName: 'Khartoum',
    CapitalLatitude: 15.6,
    CapitalLongitude: 32.533333,
    ContinentName: 'Africa',
  },
  {
    CountryName: 'Suriname',
    CapitalName: 'Paramaribo',
    CapitalLatitude: 5.833333333,
    CapitalLongitude: -55.166667,
    ContinentName: 'South America',
  },
  {
    CountryName: 'Svalbard',
    CapitalName: 'Longyearbyen',
    CapitalLatitude: 78.21666667,
    CapitalLongitude: 15.633333,
    ContinentName: 'Europe',
  },
  {
    CountryName: 'Swaziland',
    CapitalName: 'Mbabane',
    CapitalLatitude: -26.31666667,
    CapitalLongitude: 31.133333,
    ContinentName: 'Africa',
  },
  {
    CountryName: 'Sweden',
    CapitalName: 'Stockholm',
    CapitalLatitude: 59.33333333,
    CapitalLongitude: 18.05,
    ContinentName: 'Europe',
  },
  {
    CountryName: 'Switzerland',
    CapitalName: 'Bern',
    CapitalLatitude: 46.91666667,
    CapitalLongitude: 7.466667,
    ContinentName: 'Europe',
  },
  {
    CountryName: 'Syria',
    CapitalName: 'Damascus',
    CapitalLatitude: 33.5,
    CapitalLongitude: 36.3,
    ContinentName: 'Asia',
  },
  {
    CountryName: 'Taiwan',
    CapitalName: 'Taipei',
    CapitalLatitude: 25.03333333,
    CapitalLongitude: 121.516667,
    ContinentName: 'Asia',
  },
  {
    CountryName: 'Tajikistan',
    CapitalName: 'Dushanbe',
    CapitalLatitude: 38.55,
    CapitalLongitude: 68.766667,
    ContinentName: 'Asia',
  },
  {
    CountryName: 'Tanzania',
    CapitalName: 'Dar es Salaam',
    CapitalLatitude: -6.8,
    CapitalLongitude: 39.283333,
    ContinentName: 'Africa',
  },
  {
    CountryName: 'Thailand',
    CapitalName: 'Bangkok',
    CapitalLatitude: 13.75,
    CapitalLongitude: 100.516667,
    ContinentName: 'Asia',
  },
  {
    CountryName: 'Timor-Leste',
    CapitalName: 'Dili',
    CapitalLatitude: -8.583333333,
    CapitalLongitude: 125.6,
    ContinentName: 'Asia',
  },
  {
    CountryName: 'Togo',
    CapitalName: 'Lome',
    CapitalLatitude: 6.116666667,
    CapitalLongitude: 1.216667,
    ContinentName: 'Africa',
  },
  {
    CountryName: 'Tonga',
    CapitalName: "Nuku'alofa",
    CapitalLatitude: -21.13333333,
    CapitalLongitude: -175.2,
    ContinentName: 'Australia',
  },
  {
    CountryName: 'Trinidad and Tobago',
    CapitalName: 'Port of Spain',
    CapitalLatitude: 10.65,
    CapitalLongitude: -61.516667,
    ContinentName: 'North America',
  },
  {
    CountryName: 'Tunisia',
    CapitalName: 'Tunis',
    CapitalLatitude: 36.8,
    CapitalLongitude: 10.183333,
    ContinentName: 'Africa',
  },
  {
    CountryName: 'Turkey',
    CapitalName: 'Ankara',
    CapitalLatitude: 39.93333333,
    CapitalLongitude: 32.866667,
    ContinentName: 'Europe',
  },
  {
    CountryName: 'Turkmenistan',
    CapitalName: 'Ashgabat',
    CapitalLatitude: 37.95,
    CapitalLongitude: 58.383333,
    ContinentName: 'Asia',
  },
  {
    CountryName: 'Turks and Caicos Islands',
    CapitalName: 'Grand Turk',
    CapitalLatitude: 21.46666667,
    CapitalLongitude: -71.133333,
    ContinentName: 'North America',
  },
  {
    CountryName: 'Tuvalu',
    CapitalName: 'Funafuti',
    CapitalLatitude: -8.516666667,
    CapitalLongitude: 179.216667,
    ContinentName: 'Australia',
  },
  {
    CountryName: 'Uganda',
    CapitalName: 'Kampala',
    CapitalLatitude: 0.316666667,
    CapitalLongitude: 32.55,
    ContinentName: 'Africa',
  },
  {
    CountryName: 'Ukraine',
    CapitalName: 'Kyiv',
    CapitalLatitude: 50.43333333,
    CapitalLongitude: 30.516667,
    ContinentName: 'Europe',
  },
  {
    CountryName: 'United Arab Emirates',
    CapitalName: 'Abu Dhabi',
    CapitalLatitude: 24.46666667,
    CapitalLongitude: 54.366667,
    ContinentName: 'Asia',
  },
  {
    CountryName: 'United Kingdom',
    CapitalName: 'London',
    CapitalLatitude: 51.5,
    CapitalLongitude: -0.083333,
    ContinentName: 'Europe',
  },
  {
    CountryName: 'United States',
    CapitalName: 'Washington',
    CapitalLatitude: 38.883333,
    CapitalLongitude: -77,
    ContinentName: 'Central America',
  },
  {
    CountryName: 'Uruguay',
    CapitalName: 'Montevideo',
    CapitalLatitude: -34.85,
    CapitalLongitude: -56.166667,
    ContinentName: 'South America',
  },
  {
    CountryName: 'Uzbekistan',
    CapitalName: 'Tashkent',
    CapitalLatitude: 41.31666667,
    CapitalLongitude: 69.25,
    ContinentName: 'Asia',
  },
  {
    CountryName: 'Vanuatu',
    CapitalName: 'Port-Vila',
    CapitalLatitude: -17.73333333,
    CapitalLongitude: 168.316667,
    ContinentName: 'Australia',
  },
  {
    CountryName: 'Venezuela',
    CapitalName: 'Caracas',
    CapitalLatitude: 10.48333333,
    CapitalLongitude: -66.866667,
    ContinentName: 'South America',
  },
  {
    CountryName: 'Vietnam',
    CapitalName: 'Hanoi',
    CapitalLatitude: 21.03333333,
    CapitalLongitude: 105.85,
    ContinentName: 'Asia',
  },
  {
    CountryName: 'US Virgin Islands',
    CapitalName: 'Charlotte Amalie',
    CapitalLatitude: 18.35,
    CapitalLongitude: -64.933333,
    ContinentName: 'North America',
  },
  {
    CountryName: 'Wallis and Futuna',
    CapitalName: 'Mata-Utu',
    CapitalLatitude: -13.95,
    CapitalLongitude: -171.933333,
    ContinentName: 'Australia',
  },
  {
    CountryName: 'Yemen',
    CapitalName: 'Sanaa',
    CapitalLatitude: 15.35,
    CapitalLongitude: 44.2,
    ContinentName: 'Asia',
  },
  {
    CountryName: 'Zambia',
    CapitalName: 'Lusaka',
    CapitalLatitude: -15.41666667,
    CapitalLongitude: 28.283333,
    ContinentName: 'Africa',
  },
  {
    CountryName: 'Zimbabwe',
    CapitalName: 'Harare',
    CapitalLatitude: -17.81666667,
    CapitalLongitude: 31.033333,
    ContinentName: 'Africa',
  },
  {
    CountryName: 'US Minor Outlying Islands',
    CapitalName: 'Washington',
    CapitalLatitude: 38.883333,
    CapitalLongitude: -77,
    ContinentName: 'Australia',
  },
  {
    CountryName: 'Antarctica',
    CapitalName: 'N/A',
    CapitalLatitude: 0,
    CapitalLongitude: 0,
    ContinentName: 'Antarctica',
  },
  {
    CountryName: 'Northern Cyprus',
    CapitalName: 'North Nicosia',
    CapitalLatitude: 35.183333,
    CapitalLongitude: 33.366667,
    ContinentName: 'Europe',
  },
  {
    CountryName: 'Hong Kong',
    CapitalName: 'Hong Kong',
    CapitalLatitude: 0,
    CapitalLongitude: 0,
    ContinentName: 'Asia',
  },
  {
    CountryName: 'British Indian Ocean Territory',
    CapitalName: 'Diego Garcia',
    CapitalLatitude: -7.3,
    CapitalLongitude: 72.4,
    ContinentName: 'Africa',
  },
  {
    CountryName: 'Macau',
    CapitalName: 'Macau',
    CapitalLatitude: 0,
    CapitalLongitude: 0,
    ContinentName: 'Asia',
  },
];
